// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_tlH6KfKJxMu5EYwrm-xsK2N9j2dWu80',
    appId: '1:83527110089:web:2db2cecd8bcbab5a2a6c18',
    messagingSenderId: '83527110089',
    projectId: 'plant-planner-ogpnap',
    authDomain: 'plant-planner-ogpnap.firebaseapp.com',
    storageBucket: 'plant-planner-ogpnap.appspot.com',
    measurementId: 'G-B1HZD4MQJG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc7jkVOMq286Bz7In-5HFPgIDGfCHOzqg',
    appId: '1:83527110089:android:2a92d68c3c4d08022a6c18',
    messagingSenderId: '83527110089',
    projectId: 'plant-planner-ogpnap',
    storageBucket: 'plant-planner-ogpnap.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAToO7PL_LnfdhjM1_wkK8zNUXdWv9EHlM',
    appId: '1:83527110089:ios:367267db33a590f02a6c18',
    messagingSenderId: '83527110089',
    projectId: 'plant-planner-ogpnap',
    storageBucket: 'plant-planner-ogpnap.appspot.com',
    iosBundleId: 'com.csc305soft.plantplanner',
  );

}